const kelimeListesi = [
  "fikir", "yön", "baş", "son", "ilk", "düz", "eğri", "dik", "yatık", "hafif", 
  "ağır", "sığ", "bol", "az", "çok", "tam", "yarım", "çift", "kalp", "beyin", 
  "el", "göz", "kulak", "ağız", "diş", "dil", "saç", "kan", "damar", "kemik", 
  "kas", "sinir", "omuz", "kol", "sırt", "karın", "diz", "topuk", "parmak", 
  "tırnak", "yüz", "kirpik", "alın", "yanak", "çene", "dudak", "yazı", "harf", 
  "hece", "kelime", "cümle", "metin", "tarih", "bilim", "sanat", "müzik", 
  "dans", "oyun", "spor", "yüzme", "koşu", "atış", "takım", "gol", "top", 
  "kale", "file", "hakem", "tur", "yolcu", "bilet", "uçak", "tren", "araba", 
  "otobüs", "taksi", "bisiklet", "motor", "liman", "durak", "cadde", "sokak", 
  "meydan", "park", "bahçe", "tarla", "çiftlik", "fidan", "meyve", "sebze", 
  "tahıl", "ekmek", "pasta", "börek", "çorba", "et", "balık", "tavuk", "yumurta", 
  "süt", "peynir", "yoğurt", "yağ", "bal", "reçel", "şeker", "tuz", "çay", 
  "kahve", "üzüm", "erik", "vişne", "kayısı", "şeftali", "kavun", "karpuz", 
  "çilek", "fındık", "ceviz", "fıstık", "badem", "leblebi", "incir", "dut", 
  "zeytin", "marul", "lahana", "pırasa", "ıspanak", "havuç", "turp", "soğan", 
  "sarımsak", "domates", "patlıcan", "kabak", "salatalık", "fasulye", "nohut", 
  "mercimek", "pirinç", "bulgur", "un", "nişasta", "sirke", "sos", "fincan", 
  "çaydanlık", "servis", "kanepe", "yorgan", "resim", "foto", "çerçeve", 
  "vazo", "saksı", "dergi", "gazete", "şiir", "hikaye", "masal", "film", 
  "sahne", "nota", "ritim", "türkü", "beste", "konser", "klip", "kayıt", 
  "efekt", "stüdyo", "heykel", "çizim", "tasarım", "moda", "giyim", "kumaş", 
  "iplik", "düğme", "fermuar", "cep", "pantolon", "ceket", "kazak", "gömlek", 
  "tişört", "mont", "kaban", "hırka", "eldiven", "şapka", "çorap", "ayakkabı", 
  "bot", "terlik", "sandal", "yüzük", "küpe", "kolye", "bilezik", "gözlük", 
  "kemer", "şemsiye", "tarz", "stil", "trend", "ikon", "marka", "lüks", 
  "ucuz", "pahalı", "indirim", "fiyat", "kâr", "zarar", "borç", "alacak", 
  "kasa", "banka", "hesap", "bütçe", "döviz", "kur", "faiz", "vergi", "kira", 
  "maaş", "ücret", "prim", "iş", "görev", "mesai", "izin", "tatil", "kariyer", 
  "terfi", "istifa", "emekli", "yönetim", "müdür", "şef", "ekip", "proje", 
  "plan", "hedef", "vizyon", "misyon", "strateji", "taktik", "analiz", "rapor", 
  "sunum", "toplantı", "karar", "belge", "dosya", "klasör", "arşiv", "depo", 
  "stok", "nakliye", "ulaşım", "trafik", "köprü", "tünel", "hava", "uçuş", 
  "sefer", "rezerv", "otel", "pansiyon", "kamping", "turizm", "plaj", "doğa", 
  "kayak", "kamp", "çadır", "yürüyüş", "tırmanış", "futbol", "basket", "voleybol", 
  "tenis", "boks", "judo", "satranç", "tavla", "okey", "kağıt", "zar", "pullar", 
  "oyuncu", "kazanan", "kaybeden", "kupa", "madalya", "ödül", "kural", "skor", 
  "puan", "lig", "sezon", "golcü", "defans", "forvet", "kaleci", "teknik", 
  "antrenör", "kadro", "yedek", "transfer", "kulüp", "taraftar", "stad", 
  "tribün", "seyirci", "kombine", "yayın", "kanal", "spiker", "yorum", "haber", 
  "bülten", "manşet", "dakika", "canlı", "radyo", "internet", "site", "bağlantı", 
  "blog", "forum", "sosyal", "medya", "beğeni", "paylaş", "mesaj", "sohbet", 
  "video", "filtre", "emoji", "buton", "menü", "sayfa", "iletişim", "destek", 
  "yardım", "gizlilik", "şartlar", "üye", "giriş", "çıkış", "profil", "ayarlar", 
  "bildirim", "mesajlar", "arkadaş", "takipçi", "istek", "engelle", "düzenle", 
  "kaydet", "beğen", "ara", "sırala", "tüm", "popüler", "öneri", "kategori", 
  "etiket", "arama", "sonuç", "bulundu", "yükle", "tamam", "iptal", "geri", 
  "ileri", "başla", "durdur", "oynat", "sessiz", "koyu", "açık", "mod", "gece", 
  "gündüz", "otomatik", "indir", "kaldır", "hata", "uyarı", "bilgi", "başarı", 
  "şifre", "posta", "telefon", "adres", "şehir", "ilçe", "semt", "takvim", 
  "randevu", "hatırlat", "alarm", "sayaç", "yüzde", "kare", "üs", "mantık", 
  "değildir", "veya", "artı", "atama", "değer", "tür", "tip", "kapsam", "modül", 
  "paket", "platform", "sunucu", "istemci", "sorgu", "tablo", "sütun", "satır", 
  "indeks", "abajur", "acente", "adım", "afiş", "ağaç", "ahşap", "akşam", 
  "alıcı", "altay", "ambar", "anlam", "aracı", "aralık", "asmak", "avize", 
  "ayna", "babam", "bahar", "bakır", "balon", "bambu", "barın", "batak", 
  "bayan", "bebek", "beden", "belek", "belki", "berat", "besin", "beşer", 
  "beyaz", "bıçak", "bidon", "biraz", "biyel", "bizon", "boğaç", "boğaz", 
  "bohem", "bolca", "boncuk", "boran", "boyar", "bozuk", "böcek", "bölge", 
  "bölüm", "böyle", "budak", "buğra", "bulut", "burgu", "butik", "buzlu", 
  "büro", "bütün", "büyük", "cahil", "cami", "cazip", "cezve", "cılız", "cilt", 
  "cins", "cisim", "cömert", "cüce", "çaba", "çakıl", "çalar", "çanta", "çark", 
  "çekiç", "çelenk", "çerez", "çim", "çini", "çip", "çizgi", "çoban", "çözüm", 
  "daire", "dalga", "damla", "davet", "dayak", "defne", "dekor", "deniz", 
  "derin", "diken", "dinar", "dizgi", "dokuz", "dolap", "donuk", "dost", 
  "doyum", "duman", "dünya", "dürüm", "düşük", "ebedi", "ecel", "edep", "efkar", 
  "egzoz", "enfes", "engel", "ensiz", "erzak", "esans", "esir", "esnaf", "etkin", 
  "evcil", "evrak", "eylem", "fayda", "fener", "ferah", "filiz", "fiske", "fobi", 
  "forma", "fren", "füze", "galip", "gaye", "gelin", "gemici", "genel", "gergi", 
  "getiri", "gezgin", "gıda", "gölet", "görgü", "gövde", "gözcü", "grup", "gübre", 
  "güçlü", "güdü", "gülme", "gümüş", "günce", "güven", "güzel", "hacim", "hafıza", 
  "halat", "halka", "hanım", "harbi", "hatır", "havuz", "hayal", "hayat", "hazin", 
  "hızlı", "hisse", "hizmet", "hoşaf", "hurda", "ıslak", "ışık", "iade", "ibare", 
  "icmal", "idrak", "ihbar", "ikram", "iktis", "ilahi", "ilham", "imkan", "ince", 
  "irfan", "ispat", "işlem", "işsiz", "itaat", "izlem", "izmir", "jilet", "kaba", 
  "kadın", "kafes", "kalın", "kamış", "kanat", "kanca", "karde", "karlı", "kasap", 
  "kase", "katır", "kavak", "kayın", "kazan", "kebap", "kefil", "kekik", "kenar", 
  "kepçe", "kerem", "kesme", "keşif", "kibar", "kimse", "kiraz", "kirli", "kısır", 
  "kışla", "kitle", "kivi", "klima", "koçak", "kofre", "kokte", "kolay", "kolej", 
  "komik", "konak", "konu", "kopuk", "korna", "koyun", "köfte", "köy", "kredi", 
  "krema", "kriz", "kroki", "kule", "kumru", "kurgu", "kurma", "kusur", "kutu", 
  "küçük", "küp", "kürsü", "lamba", "lanet", "lazım", "lehim", "lira", "liste", 
  "lokma", "lokum", "lombo", "lütuf", "maçka", "madde", "mahir", "makam", "maket", 
  "makro", "malik", "manav", "mango", "mantar", "maske", "matem", "matiz", "mazot", 
  "melik", "merak", "mermi", "metal", "mezar", "mezun", "mihrap", "mikro", "milat", 
  "milim", "minik", "misal", "misir", "mitoz", "molla", "moruk", "motif", "muhit", 
  "mumya", "muska", "mutlu", "muzlu", "nabız", "nakil", "nakit", "namaz", "narin", 
  "nazik", "neden", "nefes", "nehir", "nemli", "nesil", "nesne", "nitel", "niyet", 
  "nizam", "nokta", "not", "nüfus", "obje", "ocak", "odun", "ofis", "okuma", "okyan", 
  "olası", "olmaz", "omlet", "onluk", "opera", "oran", "ordu", "organ", "ortak", 
  "otlak", "otluk", "oymak", "ozan", "özgür", "özlem", "özlük", "pamuk", "panda", 
  "panel", "panik", "papel", "parça", "parke", "parti", "patlı", "payda", "payet", 
  "pekin", "pelin", "pençe", "perde", "peron", "petek", "piyan", "pirin", "plaka", 
  "plaza", "polis", "pompa", "prens", "puset", "radar", "rahim", "rakip", "ramak", 
  "rampa", "ranza", "robot", "rol", "ruhsat", "rulo", "rumuz", "rüya", "sabır", 
  "safra", "sahur", "sakız", "salon", "salto", "saman", "saray", "sarı", "sarma", 
  "sauna", "sayım", "seçim", "sehim", "sekiz", "selvi", "sepet", "serap", "serin", 
  "serum", "sesli", "setir", "sevap", "seyir", "sıcak", "sıfat", "simit", "siper", 
  "siren", "sistem", "sofra", "soğuk", "sokum", "solak", "sonar", "soyut", "sözlük", 
  "suçlu", "suluk", "sumak", "surat", "susam", "şahin", "şemsi", "şubat", "şüphe", 
  "tabak", "taban", "tabip", "tabur", "tacir", "tahta", "talih", "tamir", "tanım", 
  "taraf", "tarım", "tasar", "tatlı", "tavır", "tayfa", "tayin", "teker", "tekil", 
  "tekne", "telin", "temel", "tempo", "tesis", "testi", "tetik", "tezat", "tıbbi", 
  "ticari", "tiger", "tikel", "tiner", "tipik", "tiraj", "tohum", "tokat", "tomar", 
  "tonaj", "topak", "torna", "torun", "tufan", "elida", "emel", "seçkin", "osman", 
  "korkak", "anakart", "işlemci", "casio", "abaküs", "abla", "abiye", "acı", "acil", 
  "açlık", "ada", "adak", "adale", "adam", "aday", "adet", "af", "ağ", "ağrı", 
  "ahenk", "ahize", "aile", "ak", "akçe", "akın", "akrep", "aksak", "aksiyon", "aktar", 
  "akü", "al", "ala", "alaka", "alan", "alay", "alt", "altı", "ama", "aman", "amaç", 
  "amber", "amca", "amir", "amorf", "ana", "anı", "anlık", "anma", "ansız", "ant", 
  "anut", "apak", "apart", "apiko", "arayış", "arda", "arı", "arıza", "arzu", "as", 
  "asalak", "asansör", "asıl", "asit", "aslı", "asma", "aş", "aşama", "aşçı", "aşlık", 
  "aşure", "at", "ata", "atar", "atık", "atlas", "atlı", "av", "avanak", "avare", 
  "avaz", "avcı", "avuç", "ay", "ayar", "ayaz", "aygın", "ayrı", "azade", "azam", 
  "azap", "azı", "azim", "aziz", "baba", "baca", "bacı", "bağ", "bağdaş", "bahis", 
  "bahşiş", "bak", "bakal", "bakar", "bakış", "balaban", "balcı", "balk", "balya", 
  "ban", "bandı", "bar", "baraj", "barış", "bark", "barut", "bas", "basak", "basar", 
  "bası", "baskı", "basma", "baston", "basur", "başta", "bat", "batar", "batur", 
  "bay", "bayat", "baygın", "bayır", "baykuş", "bayrak", "baz", "bazı", "beceri", 
  "bedel", "beis", "bek", "bekar", "beklenti", "bela", "belde", "belik", "belirsiz", 
  "belli", "bellek", "bemol", "ben", "bencik", "bende", "beniz", "bent", "beraat", 
  "berbat", "bere", "berk", "beş", "bet", "beton", "bey", "beyit", "bez", "bezir", 
  "bıçkı", "bıkkın", "bıyık", "bıldır", "bıkma", "bilye", "bina", "bir", "birim", 
  "birli", "bit", "bitim", "bitiş", "boş", "boğa", "boğum", "bor", "boru", "boy", 
  "boya", "boyun", "boz", "bozak", "bu", "bucak", "buda", "buğu", "buhran", "buhur", 
  "bul", "bulanık", "buluş", "bun", "burun", "buz", "bük", "bükük", "bülbül", "bürüm", 
  "büyü", "cadı", "cam", "camcı", "can", "cıva", "cıvık", "cibre", "ciddî", "cihan", 
  "cin", "cirit", "cıvata", "cıvıl", "cıvıt", "cız", "cızırtı", "cıvıltı", "cüret", 
  "cüzdan", "çakı", "çakır", "çalak", "çamur", "çanak", "çapar", "çap", "çapraş", 
  "çar", "çarık", "çatı", "çatık", "çayır", "çeki", "çelik", "çeltik", "çeper", "çeşit", 
  "çetin", "çığ", "çığlık", "çıka", "çılgın", "çın", "çırak", "çıtır", "çit", "çivi", 
  "çizik", "çörek", "çökek", "çöp", "çöplük", "çöl", "çubuk", "çukur", "çul", "çuval", 
  "dağ", "dağcı", "dahil", "dahi", "dakik", "dal", "dalak", "dalık", "dalış", "dalya", 
  "dam", "damak", "dana", "danış", "dar", "darbe", "daş", "dava", "dayı", "de", "debi", 
  "defa", "defi", "değen", "değişim", "değir", "değnek", "deh", "deha", "dek", "del", 
  "deli", "delta", "dem", "demek", "demet", "demir", "denk", "dert", "derya", "deste", 
  "dev", "deva", "devir", "dış", "dıvrak", "dıh", "dıl", "dıraz", "dır", "di", "dibek", 
  "didiş", "diğ", "dika", "dikiş", "dikme", "dikta", "dilim", "dilsiz", "dimağ", "din", 
  "dindi", "dini", "dip", "dirhem", "diri", "dışarı", "dizge", "dizi", "doğaç", "doğan", 
  "doğar", "doğru", "doğu", "doku", "dolak", "dolan", "dolar", "dolay", "dolgu", "dolma", 
  "dolu", "don", "donan", "dop", "doruk", "doygun", "doz", "dölek", "dön", "dönüm", 
  "dönüş", "dört", "düş", "düşey", "düşün", "düze", "ebabil", "ebat", "ece", "ecnebi", 
  "eda", "edim", "edit", "efendi", "efsane", "eğim", "eğin", "eğir", "eğlence", "eğme", 
  "ehil", "eke", "ekim", "ekin", "ekli", "ekran", "ela", "elçi", "elde", "elek", 
  "eleman", "elen", "elips", "elişi", "elti", "em", "emare", "emay", "emiş", "emme", 
  "emzik", "en", "enayi", "encam", "endam", "endişe", "enes", "enik", "enli", "enser", 
  "ente", "enzim", "epey", "epic", "epo", "er", "ergin", "erin", "eriş", "erk", "erke", 
  "erme", "es", "esaret", "esek", "eser", "esin", "esme", "espri", "esrik", "esse", 
  "estetik", "eş", "eşek", "eşik", "eşin", "eşit", "eşleme", "eşlik", "eşya", "etajer", 
  "etil", "etim", "etki", "etli", "etmen", "etnik", "ev", "evel", "evet", "evgi", 
  "evik", "evir", "evlek", "evli", "evren", "evrim", "evvel", "ey", "eyvah", "eylül", 
  "ezan", "ezik", "ezme", "fabrika", "facia", "fail", "fakir", "fal", "falaka", "fam", 
  "fan", "fani", "fanus", "faraş", "fark", "farz", "fasıl", "fasit", "faska", "faul", 
  "fay", "faz", "fazla", "fehim", "fek", "felak", "fena", "fer", "ferdi", "fere", 
  "feri", "feryat", "fes", "fesat", "fetih", "fetiş", "fevri", "feyz", "fıçı", "fıkra", 
  "fırça", "fırın", "fırlak", "fısıltı", "fıtık", "fiil", "fil", "filmi", "final", 
  "firar", "fire", "fiş", "fit", "fitil", "fitne", "fiya", "fizik", "fol", "fon", 
  "fors", "fos", "foya", "gaga", "gahi", "gaip", "gam", "gar", "garaj", "garb", "gari", 
  "gayet", "gayrı", "gaz", "gaza", "gazi", "gebre", "gedik", "gem", "gen", "geniş", 
  "gerdek", "germe", "gıdı", "gıyap", "gidiş", "gir", "girdi", "gidi", "git", "giz", 
  "gizem", "göbek", "göç", "göçer", "gölge", "gömme", "gömüt", "gönül", "göre", "görü", 
  "görüm", "grizu", "güce", "güdük", "güher", "gül", "güleç", "gülen", "gülü", "gün", 
  "günde", "güneş", "gür", "gürültü", "güve", "güverte", "güz", "had", "hadis", "hafız", 
  "hak", "hakan", "hal", "hala", "halk", "halta", "ham", "hamam", "hamla", "han", 
  "hane", "hani", "hantal", "hap", "haraç", "haram", "harı", "harita", "has", "hasen", 
  "haset", "hasır", "hasım", "hasis", "hasret", "hattı", "havale", "havan", "havlu", 
  "hay", "haya", "haydar", "hayır", "haylaz", "hayli", "hayta", "hazır", "heder", 
  "hekim", "helal", "hele", "helva", "hem", "hemen", "hepsi", "her", "heves", "hey", 
  "heybe", "heyet", "hız", "hızar", "hile", "hır", "hırs", "hıyar", "his", "hit", 
  "hitap", "hoca", "hod", "hol", "hor", "horoz", "hoş", "hu", "hudut", "hukuk", "hulusi", 
  "huni", "hurafe", "husus", "huzur", "hücum", "hülya", "hüner", "hür", "hüsran", 
  "ızgara", "ısrar", "ısı", "ibiş", "iblağ", "ibra", "ibret", "ibrik", "icap", "icazet", 
  "icra", "idare", "iddi", "ifa", "ifade", "iflah", "iflas", "ifrit", "iftar", "iğne", 
  "ihale", "ihlas", "ihraç", "ihtilal", "ihtiyar", "ihtiras", "ihtar", "ihvan", "iki", 
  "ikile", "ikmal", "iktisat", "iktifa", "ilan", "ilave", "ilde", "ile", "ilik", "ilim", 
  "ilke", "ilmek", "im", "imaj", "imam", "imar", "imdat", "imleç", "in", "inat", "inci", 
  "indif", "inek", "inilti", "inin", "inis", "inşah", "inzal", "ip", "ipi", "irade", 
  "iri", "irtifa", "is", "isabet", "ishak", "isim", "iskan", "iskele", "iskil", "islak", 
  "israf", "istif", "istik", "istina", "işçi", "işgal", "işık", "it", "itici", "itik", 
  "itil", "itiş", "itme", "iz", "izabe", "izah", "izam", "izle", "izzet", "jant", 
  "jarse", "jel", "jöle", "jüri", "kaan", "kabil", "kabin", "kabir", "kablo", "kabuk", 
  "kaç", "kaçak", "kaçar", "kaçış", "kadayıf", "kadeh", "kader", "kadı", "kadim", 
  "kadir", "kafi", "kafur", "kahır", "kahya", "kaide", "kakao", "kakma", "kala", 
  "kalbur", "kaldı", "kalfa", "kalıp", "kalıt", "kalkan", "kalkış", "kalkü", "kallavi", 
  "kalma", "kalori", "kalsit", "kalya", "kam", "kama", "kamçı", "kamelya", "kamus", 
  "kanaat", "kancık", "kandil", "kanıt", "kanka", "kannı", "kanun", "kap", "kapak", 
  "kapan", "kapı", "kapik", "kapma", "kaptan", "kar", "kara", "karaca", "karak", 
  "karda", "kardeş", "karık", "karıntı", "karma", "karne", "karot", "kart", "kartal", 
  "karton", "karum", "karun", "kaset", "kasık", "kasım", "kasıt", "kask", "kaslı", 
  "kasma", "kasnak", "kast", "kaşağı", "kaşar", "kaşık", "kaşkor", "kaşmir", "kat", 
  "kata", "katık", "katil", "katkı", "katla", "katlı", "katma", "katot", "kav", "kava", 
  "kaval", "kavas", "kavga", "kavik", "kavim", "kavur", "kayan", "kaygı", "kayır", 
  "kayış", "kayit", "kayma", "kaz", "kaza", "kazı", "kazık", "kazma", "kebir", "keçe", 
  "keçeli", "keçi", "keder", "kedi", "kefal", "kefen", "kek", "keklik", "kel", "kelebek", 
  "kelek", "kelem", "kelle", "kem", "keman", "kement", "kemre", "kene", "kent", "kepenk", 
  "kerde", "kere", "kerhane", "kerpiç", "kerr", "kerti", "kes", "kesat", "keser", 
  "kesi", "kesin", "kesir", "kesit", "keskin", "keş", "keşiş", "keten", "keyif", 
  "kıble", "kıdem", "kıdım", "kıh", "kılar", "kılıç", "kılıf", "kılık", "kılıs", 
  "kımıl", "kın", "kına", "kınama", "kıpır", "kıraç", "kırağı", "kiral", "kirpi", 
  "kısaca", "kısım", "kısıt", "kış", "kıtık", "kıvanç", "kıvrım", "kıyam", "kıyma", 
  "kıymet", "kıyım", "usta", "çırak", "mühendis", "doktor", "avukat", "eczacı", 
  "mimar", "pilot", "hostes", "hemşire", "gökkuşağı", "yıldırım", "şimşek", "kasırga", 
  "hortum", "zelzele", "deprem", "volkan", "mağara", "şelale", "mera", "bozkır", 
  "tundra", "kutup", "ekvator", "meridyen", "paralel", "pusula", "küre", "teleskop", 
  "mikroskop", "galaksi", "gezegen", "uydu", "yörünge", "uzay", "mars", "venüs", 
  "jüpiter", "satürn", "uranüs", "neptün", "plüton", "atom", "molekül", "enerji", 
  "kuvvet", "sürat", "ivme", "kütle", "boyut", "çevre", "köşe", "açı", "üçgen", 
  "dikdörtgen", "silindir", "prizma", "yamuk", "teğet", "kesen", "yarıçap", "kiriş", 
  "yay", "ok", "mızrak", "zırh", "miğfer", "surlar", "hendek", "burç", "sancak"
];
