const kelimeListesi = [
 "akıl", "fikir", "yön", "baş", "son", "ilk", "orta", "düz", "eğri", "dik", "yatık",
  "hafif", "ağır", "sığ", "bol", "az", "çok", "tam", "yarım", "tek", "çift",
  "kalp", "beyin", "el", "ayak", "göz", "kulak", "ağız", "diş", "dil", "saç",
  "ten", "kan", "damar", "kemik", "kas", "sinir", "omuz", "kol", "sırt",
  "karın", "diz", "topuk", "parmak", "tırnak", "yüz", "kaş", "kirpik", "alın",
  "yanak", "çene", "dudak", "yazı", "harf", "hece", "kelime", "cümle", "metin",
  "tarih", "bilim", "sanat", "müzik", "dans", "oyun", "spor", "yüzme", "koşu",
  "atış", "maç", "takım", "gol", "top", "kale", "file", "hakem", "tur", "yolcu",
  "bilet", "uçak", "tren", "gemi", "araba", "otobüs", "taksi", "bisiklet", "motor",
  "liman", "durak", "cadde", "sokak", "meydan", "park", "bahçe", "tarla", "çiftlik",
  "fidan", "meyve", "sebze", "tahıl", "ekmek", "pasta", "börek", "çorba", "et",
  "balık", "tavuk", "yumurta", "süt", "peynir", "yoğurt", "yağ", "bal", "reçel",
  "şeker", "tuz", "çay", "kahve", "elma", "armut", "üzüm", "erik", "vişne",
  "kayısı", "şeftali", "kavun", "karpuz", "çilek", "fındık", "ceviz", "fıstık",
  "badem", "leblebi", "incir", "dut", "hurma", "zeytin", "marul", "lahana",
  "pırasa", "ıspanak", "havuç", "turp", "soğan", "sarımsak", "domates", "patlıcan",
  "kabak", "salatalık", "fasulye", "nohut", "mercimek", "pirinç", "bulgur", "un",
  "nişasta", "sirke", "sos", "fincan", "çaydanlık", "servis", "kanepe", "yorgan",
  "kilim", "resim", "foto", "çerçeve", "vazo", "saksı", "dergi", "gazete", "roman",
  "şiir", "hikaye", "masal", "film", "sahne", "nota", "ritim", "şarkı", "türkü",
  "beste", "konser", "klip", "kayıt", "efekt", "stüdyo", "heykel", "çizim", "tasarım",
  "moda", "giyim", "kumaş", "iplik", "düğme", "fermuar", "cep", "yaka", "etek",
  "pantolon", "ceket", "kazak", "gömlek", "tişört", "mont", "kaban", "hırka",
  "eldiven", "şapka", "atkı", "çorap", "ayakkabı", "bot", "terlik", "sandal",
  "takı", "yüzük", "küpe", "kolye", "bilezik", "gözlük", "kemer", "şemsiye",
  "tarz", "stil", "trend", "ikon", "marka", "lüks", "ucuz", "pahalı", "indirim",
  "fiyat", "kâr", "zarar", "borç", "alacak", "kasa", "banka", "hesap", "bütçe",
  "döviz", "kur", "faiz", "vergi", "kira", "maaş", "ücret", "prim", "iş", "görev",
  "mesai", "izin", "tatil", "kariyer", "terfi", "istifa", "emekli", "yönetim",
  "müdür", "şef", "ekip", "proje", "plan", "hedef", "vizyon", "misyon", "strateji",
  "taktik", "analiz", "rapor", "sunum", "toplantı", "karar", "imza", "belge",
  "dosya", "klasör", "arşiv", "depo", "stok", "nakliye", "ulaşım", "trafik",
  "köprü", "tünel", "hava", "uçuş", "sefer", "rezerv", "otel", "pansiyon",
  "kamping", "turizm", "gezi", "plaj", "doğa", "kayak", "kamp", "çadır", "yürüyüş",
  "tırmanış", "futbol", "basket", "voleybol", "tenis", "boks", "judo", "satranç",
  "tavla", "okey", "kağıt", "zar", "pullar", "oyuncu", "kazanan", "kaybeden",
  "kupa", "madalya", "ödül", "kural", "skor", "puan", "lig", "sezon",
  "golcü", "defans", "forvet", "kaleci", "teknik", "antrenör", "kadro", "yedek",
  "transfer", "kulüp", "taraftar", "stad", "tribün", "seyirci", "kombine", "yayın",
  "kanal", "spiker", "yorum", "haber", "bülten", "manşet", "dakika", "canlı",
  "radyo", "internet", "site", "bağlantı", "blog", "forum", "sosyal", "medya",
  "takip", "beğeni", "paylaş", "mesaj", "sohbet", "video", "filtre", "emoji",
  "buton", "menü", "sayfa", "iletişim", "destek", "yardım", "gizlilik", "şartlar",
  "üye", "kayıt", "giriş", "çıkış", "profil", "ayarlar", "bildirim", "mesajlar",
  "arkadaş", "takipçi", "istek", "engelle", "düzenle", "kaydet", "beğen",
  "ara", "sırala", "tüm", "popüler", "öneri", "kategori",
  "etiket", "arama", "sonuç", "bulundu", "yükle", "tamam", "iptal", "geri", "ileri",
  "başla", "durdur", "oynat", "sessiz", "koyu", "açık", "mod", "gece", "gündüz",
  "otomatik", "indir", "kaldır", "hata", "uyarı", "bilgi", "başarı",
  "şifre", "posta", "telefon", "adres", "şehir", "ilçe", "semt", "takvim", "randevu",
  "hatırlat", "alarm", "sayaç", "yüzde", "kare", "üs", "sabit", "mantık", "değildir", "veya", "artı", "eksi",
  "atama", "değer", "tür", "tip", "kapsam", "modül", "paket", "çerçeve", "platform",
  "sunucu", "istemci", "sorgu", "tablo", "sütun", "satır", "indeks", "abajur", "acente",
  "adım", "afiş", "ağaç", "ahşap", "akşam", "alıcı", "altay", "ambar",
  "anlam", "araba", "aracı", "aralık", "asmak", "avize", "aylak", "ayna", "babam",
  "bahar", "bahçe", "bakır", "balon", "bambu", "banka", "barın", "basit", "batak", "bayan",
  "bebek", "beden", "belek", "belki", "berat", "besin", "beşer", "beyaz", "bıçak",
  "bidon", "bilgi", "bilet", "biraz", "bitki", "biyel", "bizon", "boğaç", "boğaz", "bohem",
  "bolca", "boncuk", "boran", "boyar", "bozuk", "böcek", "bölge", "bölüm", "börek", "böyle",
  "budak", "buğra", "bulut", "burgu", "butik", "buzlu", "büro", "bütün", "büyük",
  "cadde", "cahil", "cami", "canlı", "cazip", "ceviz", "cezve", "cılız", "cilt", "cins",
  "cisim", "cömert", "cüce", "çaba", "çadır", "çakıl", "çalar", "çanta", "çark", "çekiç",
  "çelenk", "çene", "çerez", "çilek", "çim", "çini", "çip", "çizgi", "çoban", "çorba", "çözüm",
  "daire", "dalga", "damar", "damla", "davet", "dayak", "defne", "dekor", "delik", "deniz",
  "dergi", "derin", "diken", "dilek", "dinar", "dizgi", "doğa", "dokuz", "dolap", "donuk",
  "dost", "doyum", "duman", "dünya", "dürüm", "düşük", "ebedi", "ecel", "edep", "efkar",
  "egzoz", "eklem", "ekmek", "elmas", "emlak", "enfes", "engel", "ensiz",
  "erzak", "esans", "esir", "esnaf", "etkin", "evcil", "evrak", "eylem", "fayda", "fener",
  "ferah", "fidan", "fikir", "filiz", "fiske", "fobi", "forma", "fren", "füze",
  "galip", "gaye", "gelin", "gemici", "genel", "gergi", "getiri", "gezgin", "gıda", "giyim",
  "gölet", "görgü", "gövde", "gözcü", "grup", "gübre", "güçlü", "güdü", "gülme", "gümüş",
  "günce", "güven", "güzel", "hacim", "hafıza", "hakem", "halat", "halka", "hamur", "hanım",
  "harbi", "harf", "hasat", "hasta", "hatır", "havuz", "hayal", "hayat", "hazin", "hızlı",
  "hisse", "hizmet", "hoşaf", "hurda", "ıslak", "ışık", "iade", "ibare", "icmal",
  "idrak", "ihbar", "iklim", "ikram", "iktis", "ilahi", "ilham", "ilk", "imal", "imkan",
  "ince", "indir", "iplik", "irfan", "ispat", "işlem", "işsiz", "itaat", "izlem",
  "izmir", "jilet", "judo", "kaba", "kadın", "kafes", "kahve", "kalem", "kalın", "kamış",
  "kanal", "kanat", "kanca", "karde", "karış", "karlı", "kasap", "kase", "katip", "katır",
  "kavak", "kavun", "kayak", "kayık", "kayın", "kazak", "kazan", "kebap", "kefil", "kekik",
  "kelam", "kemer", "kenar", "kepçe", "kerem", "kesik", "kesme", "keşif", "kibar", "kiler",
  "kilit", "kimse", "kira", "kiraz", "kirli", "kısır", "kışla", "kitle", "kivi", "klasör",
  "klima", "koçak", "kofre", "kokte", "kolay", "kolej", "kolye", "komik", "konak", "konu",
  "kopuk", "korna", "koyun", "köfte", "köprü", "köy", "kredi", "krema", "kriz", "kroki",
  "kule", "kulüp", "kumru", "kural", "kurgu", "kurma", "kusur", "kutu", "küçük",
  "küp", "kürsü", "lamba", "lanet", "lazım", "lehim", "liman",
  "lira", "liste", "lokma", "lokum", "lombo", "lütuf", "maçka", "madde", "mahir",
  "makam", "maket", "makro", "malik", "manav", "mango", "manşet", "mantar", "marul", "masal",
  "maske", "matem", "matiz", "mazot", "melek", "melik", "menü", "merak", "mermi", "mesaj",
  "mesai", "metal", "metin", "mezar", "mezun", "mihrap", "mikro", "milat", "milim", "minik",
  "misal", "misir", "mitoz", "modül", "molla", "mont", "moruk", "motif", "motor",
  "muhit", "mumya", "murat", "muska", "mutlu", "muzlu", "nabız", "nakil", "nakit", "namaz",
  "narin", "nazik", "neden", "nefes", "nehir", "nemli", "nesil", "nesne", "net", "nitel",
  "niyet", "nizam", "nokta", "not", "nüfus", "obje", "ocak", "odun", "ofis", "okuma", "okyan",
  "olası", "olmaz", "omlet", "onluk", "opera", "oran", "ordu", "organ", "ortak", "otlak",
  "otluk", "oymak", "ozan", "özgür", "özlem", "özlük", "paket", "palet", "palto", "pamuk",
  "panda", "panel", "panik", "papel", "parça", "parke", "parti", "patik", "patlı", "payda",
  "payet", "pekin", "pelin", "pençe", "perde", "peron", "petek", "piyan", "pirin", "plaka",
  "plan", "plaza", "polis", "pompa", "posta",  "prens", "proje", "puan", "puset",
  "radar", "radyo", "raf", "rahim", "rakip", "ramak", "rampa", "ranza", "rapor", "resim",
  "ritim", "robot", "rol", "roman", "rota", "ruhsat", "rulo", "rumuz", "rüya", "sabır",
  "sabit", "safra", "sahne", "sahur", "sakız", "salon", "salto", "saman", "sanat", "saray",
  "sarı", "sarma", "satır", "sauna", "sayfa", "sayım", "seçim", "sefer", "sehim", "sekiz",
  "selam", "selvi", "sepet", "serap", "serin", "serum", "sesli", "setir", "sevap", "seyir",
  "sıcak", "sıfat", "sıkma", "simit", "sinir", "siper", "siren", "sistem", "sofra",
  "soğuk", "sokak", "sokum", "solak", "sonar", "sonuç", "sorgu", "soyut", "sözlük",
  "spiker", "spor", "suçlu", "suluk", "sumak", "sunum", "surat", "susam", "sütun", "şahin",
  "şapka", "şarkı", "şeker", "şemsi", "şifre", "şubat", "şüphe", "tabak", "taban", "tabip",
  "tablo", "tabur", "tacir", "tahta", "takım", "takip", "taksi", "talep", "talih",
  "tamir", "tanım", "taraf", "tarım", "tasar", "tatlı", "tavır", "tavuk", "tayfa", "tayin",
  "teker", "tekil", "tekne", "telin", "temel", "tempo", "tenis", "tesis", "testi", "tetik",
  "tezat", "tıbbi", "ticari", "tiger", "tikel", "tilki", "tiner", "tipik", "tiraj", 
  "tohum", "tokat", "tomar", "tonaj", "topak", "topla", "torna", "torun", "tufan", "elida",
  "emel", "seçkin", "osman", "korkak", "anakart", "işlemci", "casio", "abaküs", "abla", "abiye", 
  "acı", "acil", "açlık", "ada", "adak", "adale", "adam", "aday", "adet", "af", "afiş", "ağ", 
  "ağaç", "ağrı", "ahenk", "ahize", "aile", "ak", "akçe", "akın", "akrep", "aksak", "aksiyon", 
  "aktar", "akü", "al", "ala", "alaka", "alan", "alay", "alçı", "alem", "alev", "algı", "alıcı", 
  "alim", "alış", "alkış", "allı", "alp", "alt", "altı", "ama", "aman", "amaç", "amber", "amca", 
  "amir", "amorf", "ana", "anı", "anlık", "anma", "ansız", "ant", "anut", "apak", "apart", "apiko", 
  "ara", "aralık", "arayış", "arda", "arı", "arıza", "arzu", "as", "asalak", "asansör", "asıl", 
  "asit", "askı", "aslı", "asma", "aş", "aşama", "aşçı", "aşk", "aşlık", "aşure", "at", "ata",
  "atar", "atık", "atış", "atkı", "atlas", "atlı", "av", "avanak", "avare", "avaz", "avcı", 
  "avuç", "ay", "ayak", "ayar", "ayaz", "aygın", "aylak", "ayna", "ayrı", "az", "azade", "azam",  
  "azap", "azı", "azim", "aziz", "baba", "baca", "bacı", "bağ", "bağdaş", "bahçe", "bahis",
  "bahşiş", "bak", "bakal", "bakar", "bakış", "bal", "balaban", "balcı", "balık", "balk", 
  "balya", "ban", "bandı", "bar", "baraj", "barış", "bark", "barut", "bas", "basak", "basar", 
  "bası", "baskı", "basma", "baston", "basur", "baş", "başta", "bat", "batak", "batar", "batur", 
  "bay", "bayat", "baygın", "bayır", "baykuş", "bayrak", "baz", "bazı", "beceri", "bedel", 
  "beden", "beis", "bek", "bekar", "beklenti", "bela", "belde", "belek", "belik", "belirsiz", 
  "belli", "bellek", "bemol", "ben", "bencik", "bende", "beniz", "bent", "beraat", "berbat",
  "bere", "berk", "besin", "beste", "beş", "beşer", "bet", "beton", "bey", "beyin", "beyit", 
  "bez", "bezir", "bıçkı", "bıkkın", "bıyık", "bıçak", "bıldır", "bıkma", "bilye", "bina", "bir", 
  "birim", "birli", "bit", "bitik", "bitim", "bitiş", "bitki", "bizon", "bıyık", "boş", "boğa",
  "boğum", "bohem", "bol", "bor", "boru", "boy", "boya", "boyun", "boz", "bozak", "bu", "bucak",
  "buda", "buğu", "buhran", "buhur", "bul", "bulak", "bulanık", "bulgur", "buluş", "bulut",
  "bun", "burgu", "burun", "buz", "büro", "bük", "bükük", "bülbül", "bürüm", "bütçe", "bütün",
  "büyü", "büyük", "cadı", "cam", "camcı", "can", "cıva", "cılız", "cıvık", "cibre", "ciddî",
  "cihan", "cilt", "cin", "cins", "cirit", "cıvata", "cıvıl", "cıvıt", "cız", "cızırtı",
  "cıvıltı", "cüce", "cüret", "cüzdan", "çaba", "çakı", "çakıl", "çakır", "çalak", "çalı",
  "çam", "çamur", "çanak", "çapar", "çap", "çapraş", "çar", "çarık", "çark", "çatı", "çatık", 
  "çay", "çayır", "çeki", "çelik", "çeltik", "çene", "çeper", "çeşit", "çetin", "çığ", 
  "çığlık", "çıka", "çıkış", "çılgın", "çın", "çırak", "çıtır", "çit", "çivi", "çizgi", "çizik",
  "çok", "çorap", "çörek", "çökek", "çözüm", "çöp", "çöplük", "çöl", "çubuk", "çukur",
  "çul", "çuval", "dağ", "dağcı", "dahil", "dahi", "daire", "dakik", "dal", "dalak", "dalga",
  "dalık", "dalış", "dalya", "dam", "damak", "damar", "damla", "dana", "danış", "dar", "darbe",
  "daş", "dava", "dayı", "de", "debi", "defa", "defi", "değen", "değer", "değişim", 
  "değir", "değnek", "deh", "deha", "dek", "del", "delik", "deli", "delta", "dem",
  "demek", "demet", "demir", "denk", "derin", "dert", "derya", "deste", "dev", "deva",
  "devir", "dış", "dıvrak", "dıh", "dıl", "dıraz", "dır", "di", "dibek", "didiş", "diğ",
  "dik", "dika", "dikiş", "dikme", "dikta", "dil", "dilek", "dilim", "dilsiz", "dimağ",
  "din", "dindi", "dini", "dip", "dirhem", "diri", "diş", "dışarı", "diz", "dizge",
  "dizi", "doğa", "doğaç", "doğan", "doğar", "doğru", "doğu", "doku", "dokuz", "dolak",
  "dolan", "dolar", "dolay", "dolgu", "dolma", "dolu", "don", "donan", "donuk", "dop", 
  "doruk", "dost", "doygun", "doyum", "doz", "dölek", "dön", "dönüm", "dönüş", "dört", 
  "düş", "düşey", "düşük", "düşün", "düz", "düze", "ebabil", "ebat", "ebedi", "ece", "ecel", 
  "ecnebi", "eda", "edep", "edim", "edit", "efendi", "efsane", "egzoz", "eğim", "eğin", "eğir", 
  "eğlence", "eğme", "eğri", "ehil", "eke", "ekim", "ekin", "eklem", "ekli", "ekmek", "ekran", 
  "eksik", "el", "ela", "elçi", "elde", "elek", "eleman", "elen", "elips", "elişi", "elmas", "elti",
  "em", "emare", "emay", "emel", "emin", "emir", "emiş", "emlak", "emme", "emzik", "en", "enayi",
  "encam", "endam", "endişe", "enes", "engel", "enik", "enli", "enser", "ente", "enzim", "epey",
  "epic", "epo", "er", "ergin", "erik", "erim", "erin", "eriş", "erk", "erke", "erlik", "erme",
  "erzak", "es", "esans", "esaret", "esek", "eser", "esin", "esir", "eski", "esme", "esnaf",
  "espri", "esrik", "esse", "estetik", "eş", "eşek", "eşik", "eşin", "eşit", "eşleme", "eşlik", "eşya", 
  "et", "etajer", "etek", "etil", "etim", "etki", "etli", "etmen", "etnik", "ev", "evcil", "evel", "evet",
  "evgi", "evik", "evir", "evlek", "evli", "evrak", "evren", "evrim", "evvel", "ey", "eyvah", "eylül",
  "eylem", "ezan", "ezgi", "ezik", "ezme", "fabrika", "facia", "fail", "fakir", "fal", "falaka", "fam",
  "fan", "fani", "fanus", "far", "faraş", "fark", "farz", "fasıl", "fasit", "faska", "faul", "fay", "fayda",
  "faz", "fazla", "fehim", "fek", "felak", "fena", "fener", "fer", "ferah", "ferdi", "fere", "feri", "feryat",
  "fes", "fesat", "fetih", "fetiş", "fevri", "feyz", "fıçı", "fidan", "fıkra", "fındık", "fırça", "fırın", 
  "fırlak", "fısıltı", "fıtık", "fikir", "fiil", "fil", "filiz", "filmi", "final", "firar", "fire", "fiske",
  "fiş", "fit", "fitil", "fitne", "fiya", "fizik", "fobi", "fol", "fon", "forma", "fors", "fos", "foya", 
  "fren", "füze", "gaga", "gahi", "gaip", "galip", "gam", "gar", "garaj", "garb", "gari", "gaye", 
  "gayet", "gayrı", "gaz", "gaza", "gazi", "gebre", "gece", "gedik", "gelin", "gem", "gemi", "gen",
  "genel", "geniş", "gerdek", "gergi", "geri", "germe", "gıdı", "gıda", "gıyap", "gidiş", "gir",
  "girdi", "gidi", "git", "giz", "gizem", "göbek", "göç", "göçer", "gölge", "gömme", "gömüt",
  "gönül", "göre", "görev", "görgü", "görü", "görüm", "gövde", "göz", "gözcü", "grizu", "grup",
  "gübre", "güce", "güçlü", "güdük", "güdü", "güher", "gül", "güleç", "gülen", "gülme", "gülü",
  "gümüş", "gün", "günce", "günde", "güneş", "gür", "gürültü", "güve", "güven", "güverte", "güz",
  "güzel", "hacim", "had", "hadis", "hafız", "hafif", "hak", "hakan", "hakem", "hal", "hala",
  "halat", "halk", "halka", "halta", "ham", "hamam", "hamla", "hamur", "han", "hane", "hani", 
  "hantal", "hap", "haraç", "haram", "harbi", "harf", "harı", "harita", "has", "hasat", "hasen", "haset",
  "hasır", "hasım", "hasis", "hasret", "hasta", "hata", "hatır", "hattı", "hava", "havale", "havan", "havlu",
  "havuz", "hay", "haya", "hayal", "hayat", "haydar", "hayır", "haylaz", "hayli", "hayta", "hazır", "hece", 
  "hedef", "heder", "hekim", "helal", "hele", "helva", "hem", "hemen", "hepsi", "her", "hesap", "heves", "hey",
  "heybe", "heyet", "hız", "hızar", "hızlı", "hile", "hır", "hırs", "hıyar", "his", "hisse", "hit", "hitap", "hız",
  "hoca", "hod", "hol", "hor", "horoz", "hoş", "hu", "hudut", "hukuk", "hulusi", "huni", "hurafe", "hurda", "hurma", 
  "husus", "huzur", "hücum", "hülya", "hüner", "hür", "hüsran", "ızgara", "ırak", "ıslak", "ısrar", "ısı", "ışık",
  "iade", "ibare", "ibiş", "iblağ", "ibra", "ibret", "ibrik", "icap", "icazet", "icra", "idare", "iddi", "idrak", 
  "ifa", "ifade", "iflah", "iflas", "ifrit", "iftar", "iğne", "ihale", "ihbar", "ihlas", "ihraç", "ihtilal", "ihtiyar",
  "ihtiras", "ihtar", "ihvan", "iki", "ikile", "iklim", "ikmal", "ikon", "ikram", "iktisat", "iktifa", "ilahi", 
  "ilam", "ilan", "ilave", "ilçe", "ilde", "ile", "ilham", "ilik", "ilim", "ilke", "ilmek", "im", "imaj", "imal",
  "imam", "imar", "imdat", "imge", "imkan", "imleç", "imza", "in", "inat", "inci", "incir", "indif", "indir",
  "inek", "inilti", "inin", "inis", "inme", "inşah", "inzal", "ip", "ipi", "iplik", "irade", "irfan", "iri",
  "irtifa", "is", "isabet", "ishak", "isim", "iskan", "iskele", "iskil", "islak", "ispat", "israf", "istif",
  "istik", "istina", "iş", "işçi", "işgal", "işık", "işlem", "işsiz", "it", "itaat", "itici", "itik", "itil",
  "itiş", "itme", "iz", "izabe", "izah", "izam", "izin", "izlem", "izle", "izzet", "jant", "jarse", "jel", 
  "jilet", "jöle", "jüri", "kaan", "kaba", "kabak", "kabil", "kabin", "kabir", "kablo", "kabuk", "kabul",
  "kaç", "kaçak", "kaçar", "kaçış", "kadayıf", "kadeh", "kader", "kadı", "kadim", "kadir", "kadro", "kafes",
  "kafi", "kafur", "kağıt", "kahır", "kahve", "kahya", "kaide", "kakao", "kakma", "kala", "kalay", "kalbur",
  "kaldı", "kalem", "kalfa", "kalın", "kalıp", "kalıt", "kalkan", "kalkış", "kalkü", "kallavi", "kalma", 
  "kalori", "kalp", "kalsit", "kalya", "kam", "kama", "kamçı", "kamelya", "kamış", "kamp", "kamus", "kan",
  "kanaat", "kanal", "kanat", "kanca", "kancık", "kandil", "kanıt", "kanka", "kannı", "kanun", "kap", "kapak", 
  "kapan", "kapı", "kapik", "kapma", "kaptan", "kar", "kara", "karaca", "karak", "karar", "karda", "kardeş",
  "karı", "karık", "karın", "karıntı", "karış", "karlı", "karma", "karne", "karot", "karşı", "kart", "kartal",
  "karton", "karum", "karun", "kas", "kasa", "kasap", "kase", "kaset", "kasık", "kasım", "kasıt", "kask", "kaslı",
  "kasma", "kasnak", "kast", "kaş", "kaşağı", "kaşar", "kaşık", "kaşkor", "kaşmir", "kat", "kata", "katı", "katık",
  "katil", "katip", "katkı", "katla", "katlı", "katma", "katot", "kav", "kava", "kavak", "kaval", "kavas",
  "kavga", "kavik", "kavim", "kavun", "kavur", "kaya", "kayak", "kayan", "kaygı", "kayık", "kayın", "kayır",
  "kayış", "kayit", "kayma", "kaz", "kaza", "kazak", "kazan", "kazı", "kazık", "kazma", "kebap", "kebir", 
  "keçe", "keçeli", "keçi", "keder", "kedi", "kefal", "kefen", "kefil", "kek", "kekik", "keklik", "kel",
  "kelebek", "kelek", "kelem", "kelime", "kelle", "kem", "keman", "kement", "kemer", "kemik", "kemre", 
  "kenar", "kene", "kent", "kepçe", "kepenk", "kerde", "kere", "kerem", "kerhane", "kerpiç", "kerr",
  "kerti", "kes", "kesat", "keser", "kesi", "kesik", "kesin", "kesir", "kesit", "keskin", "kesme",
  "keş", "keşif", "keşiş", "ket", "kete", "keten", "keyif", "kıble", "kıdem", "kıdım", "kıh", "kıla",
  "kılar", "kılıç", "kılıf", "kılık", "kılıs", "kımıl", "kın", "kına", "kınama", "kıpır", "kıraç",
  "kırağı", "kiral", "kiraz", "kirli", "kirpi", "kısa", "kısaca", "kısım", "kısır", "kısıt", "kısma",
  "kış", "kışla", "kıta", "kıtık", "kıvanç", "kıvrım", "kıyak", "kıyam", "kıyma", "kıymet", "kıyım"
];





